### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by pierreganty** [vhavlena/ranker#27]
Hi,

when running `ranker` on the file [`fischerv3B`](https://github.com/parof/buchi-automata-benchmark/blob/master/benchmark/rabit/included/fischerv3/fischerV3B.ba) in BA format I am getting 
```
HOA: v1
States: 1
Start: 0
acc-name: Buchi
Acceptance: 1 Inf(0)
properties: trans-labels explicit-labels state-acc
AP: 2 "0" "1"
--BODY--
State: 0 {0}
[!0&1] 0
[0&!1] 0
--END--
```
which is a "universal" automata in that setting (the alphabet of `fischerV3B.ba` being binary).
It is unexpected as the language of `fischerV3B.ba` is non empty (confirmed by GOAL).

**Comment by vhavlena** [comment]
Thanks for the report. It should be working now (a bug in the parser).
