### ISSUE TITLE
Issue with temporary Hanoi files

### ISSUE THREAD

**Issue by pierreganty** [vhavlena/ranker#28]
Dear ranker developers,

The command `ranker <(cat automaton.ba)` runs as expected but `ranker <(cat automaton.hoa)` does not (while `ranker automaton.hoa` runs fine).
In particular `ranker <(cat automaton.hoa)` returns `Error: Unsupported automaton type`.

Thank you,
Pierre

**Comment by vhavlena** [comment]
Dear Pierre,
unfortunately it is not currently possible to use the temporary files the way you do. I guess the problem is that for some settings the input file is being read multiple times. But, I at least added a possibility to read automata from the standard input.
